Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.

Mappings:
  CommunitiesAllowedOriginMap:
    dev:
      "AllowedOrigin": "https://*.access-funding.dev.communities.gov.uk"
    test:
      "AllowedOrigin": "https://*.access-funding.test.communities.gov.uk"
    uat:
      "AllowedOrigin": "https://*.access-funding.uat.communities.gov.uk"
    prod:
      "AllowedOrigin": "https://*.access-funding.communities.gov.uk"

Resources:
  FormUploadsBucket:
    Metadata:
      'aws:copilot:description': 'An Amazon S3 bucket, form-uploads, for storing and retrieving objects'
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub fsd-form-uploads-${Env}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
            AllowedOrigins:
              - "https://*.access-funding.test.levellingup.gov.uk"
              - "https://*.access-funding.levellingup.gov.uk"
              - !FindInMap [CommunitiesAllowedOriginMap, !Ref Env, 'AllowedOrigin']
            MaxAge: '3000'
      LoggingConfiguration:
        DestinationBucketName: !Ref FormUploadsLogBucket
        LogFilePrefix: logs/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  FormUploadsLogBucket:
    Metadata:
      'aws:copilot:description': 'An Amazon S3 bucket, form-uploads-logs, for access control logs'
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub fsd-form-uploads-logs-${Env}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  FormUploadsBucketPolicy:
    Metadata:
      'aws:copilot:description': 'A bucket policy to deny unencrypted access to the bucket and its contents'
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowGuardDutyToManageNotifications
            Effect: Allow
            Principal:
              Service: guardduty.amazonaws.com
            Action:
              - s3:GetBucketNotification
              - s3:PutBucketNotification
            Resource: !Sub ${ FormUploadsBucket.Arn}
          - Sid: ForceHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub ${ FormUploadsBucket.Arn}/*
              - !Sub ${ FormUploadsBucket.Arn}
            Condition:
              Bool:
                "aws:SecureTransport": false
      Bucket: !Ref FormUploadsBucket

  FormUploadsLogBucketPolicy:
    Metadata:
      'aws:copilot:description': 'A bucket policy to allow logs to be sent to the access log bucket'
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref FormUploadsLogBucket
                - /*
            Condition:
              ArnLike:
                'aws:SourceArn': !GetAtt
                  - FormUploadsBucket
                  - Arn
              StringEquals:
                'aws:SourceAccount': !Sub '${AWS::AccountId}'
      Bucket: !Ref FormUploadsLogBucket

  FormsUploadBucketAccessPolicy:
     Type: AWS::IAM::ManagedPolicy
     Properties:
       PolicyDocument:
         Version: '2012-10-17'
         Statement:
           - Sid: S3FormUploadActions
             Effect: Allow
             Action:
               - s3:Get*
               - s3:List*
               - s3:Describe*
               - s3:PutObject
               - s3:PutObjectACL
               - s3:DeleteObject
               - s3:ReplicateObject
             Resource:
               - !Sub ${ FormUploadsBucket.Arn }
               - !Sub ${ FormUploadsBucket.Arn }/*

  GuardDutyS3MalwareScanRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: malware-protection-plan.guardduty.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GuardDutyS3MalwareScanPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow GuardDuty to configure MalwareProtectionPlan
              - Sid: AllowCreatePlan
                Effect: Allow
                Action: guardduty:CreateMalwareProtectionPlan
                Resource: '*'

              # Allow GuardDuty to assume this role
              - Sid: AllowPassRole
                Effect: Allow
                Action: iam:PassRole
                Resource: '*'
                Condition:
                  StringEquals:
                    iam:PassedToService: malware-protection-plan.guardduty.amazonaws.com

              # S3 – bucket-level notifications & ownership validations
              - Sid: AllowEnableS3EventBridgeEvents
                Effect: Allow
                Action:
                  - s3:PutBucketNotification
                  - s3:GetBucketNotification
                Resource: !Sub ${ FormUploadsBucket.Arn}

              - Sid: AllowS3BucketOwnershipChecks
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketTagging
                  - s3:GetBucketLocation
                  - s3:GetBucketPolicyStatus
                  - s3:GetBucketAcl
                Resource: !Sub ${ FormUploadsBucket.Arn}

              # S3 – object-level scanning and tagging
              - Sid: AllowMalwareScanAndTag
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObjectTagging
                  - s3:GetObjectTagging
                  - s3:PutObjectVersionTagging
                  - s3:GetObjectVersionTagging
                Resource:
                  - !Sub ${ FormUploadsBucket.Arn}/*

              # S3 – test object validation
              - Sid: AllowPutValidationObject
                Effect: Allow
                Action: s3:PutObject
                Resource: !Sub ${ FormUploadsBucket.Arn}/malware-protection-resource-validation-object

              # EventBridge – required managed rule lifecycle actions
              - Sid: AllowManagedRuleToSendS3EventsToGuardDuty
                Effect: Allow
                Action:
                  - events:PutRule
                  - events:DeleteRule
                  - events:PutTargets
                  - events:RemoveTargets
                Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/DO-NOT-DELETE-AmazonGuardDutyMalwareProtectionS3*
                Condition:
                  StringLike:
                    events:ManagedBy: malware-protection-plan.guardduty.amazonaws.com

              - Sid: AllowGuardDutyToMonitorEventBridgeManagedRule
                Effect: Allow
                Action:
                  - events:DescribeRule
                  - events:ListTargetsByRule
                Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/DO-NOT-DELETE-AmazonGuardDutyMalwareProtectionS3*

  S3MalwareProtectionPlan:
    Type: AWS::GuardDuty::MalwareProtectionPlan
    Properties:
      Role: !GetAtt GuardDutyS3MalwareScanRole.Arn
      ProtectedResource:
        S3Bucket:
          BucketName: !Ref FormUploadsBucket
      Actions:
        Tagging:
          Status: ENABLED
    DependsOn:
      - GuardDutyS3MalwareScanRole

Outputs:
  MalwareProtectionPlanRoleArn:
    Description: ARN of the IAM Role used by the Malware Protection Plan
    Value: !GetAtt GuardDutyS3MalwareScanRole.Arn
  FormUploadsName:
    Description: "The name of a user-defined bucket."
    Value: !Ref FormUploadsBucket
    Export:
      Name: !Sub ${App}-${Env}-FormUploadsBucket
  FormUploadsBucketARN:
    Description: "The ARN of the form-uploads bucket."
    Value: !GetAtt FormUploadsBucket.Arn
    Export:
      Name: !Sub ${App}-${Env}-FormUploadsBucketARN
  FormsUploadBucketAccessPolicyArn:
    Description: "The ARN of the Forms Upload bucket access policy to attach to the task role"
    Value: !Ref FormsUploadBucketAccessPolicy
    Export:
      Name: !Sub ${App}-${Env}-FormsUploadBucketAccessPolicyArn
